name: 'Compute Config variables'

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.10"
      plone-version:
        required: false
        type: string
        default: "6.1.3"
    outputs:
      backend:
        description: "Flag reporting if we should run the backend jobs"
        value: ${{ jobs.config.outputs.backend }}
      base-tag:
        description: "Base tag to be used when creating container images"
        value: ${{ jobs.config.outputs.base-tag }}
      docs:
        description: "Flag reporting if we should run the docs jobs"
        value: ${{ jobs.config.outputs.docs }}
      python-version:
        description: "Python version to be used"
        value: ${{ inputs.python-version }}
      plone-version:
        description: "Plone version to be used"
        value: ${{ inputs.plone-version }}

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      docs: ${{ steps.filter.outputs.docs }}
      plone-version: ${{ steps.vars.outputs.plone-version }}
      base-tag: ${{ steps.vars.outputs.base-tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Compute several vars needed for the CI
        id: vars
        run: |
          echo "base-tag=sha-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "plone-version=${{ inputs.plone-version }}" >> $GITHUB_OUTPUT

      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            backend:
              - '**'
              - '.github/workflows/*.yml'
            docs:
              - '.readthedocs.yaml'
              - 'docs/**'

      - name: Test vars
        run: |
          echo "base-tag: ${{ steps.vars.outputs.base-tag }}"
          echo 'plone-version: ${{ steps.vars.outputs.plone-version }}'
          echo 'event-name: ${{ github.event_name }}'
          echo "ref-name: ${{ github.ref_name }}"
          echo 'Paths - backend: ${{ steps.filter.outputs.backend }}'
          echo 'Paths - docs: ${{ steps.filter.outputs.docs }}'
