name: plone-stubs CI

on:
  push:

jobs:

  config:
    name: "Compute configuration values"
    uses: ./.github/workflows/config.yml

  docs:
    name: "Generate documentation"
    uses: plone/meta/.github/workflows/docs-build.yml@2.x
    needs:
      - config
    with:
      python-version: ${{ needs.config.outputs.python-version }}
      working-directory: "docs"
      check-links: true
      check-vale: true

  lint:
    name: "Lint codebase"
    uses: plone/meta/.github/workflows/backend-lint.yml@2.x
    needs:
      - config
    with:
      python-version: ${{ needs.config.outputs.python-version }}
      plone-version:  ${{ needs.config.outputs.plone-version }}
      check-typing: false

  report:
    name: "Final report"
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - config
      - lint
      - docs
    steps:
      - name: Report
        shell: bash
        run: |
          echo '# Workflow Report' >> $GITHUB_STEP_SUMMARY
          echo '| Job ID | Conclusion |' >> $GITHUB_STEP_SUMMARY
          echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
          echo '| Config | ${{ needs.config.result }} |' >> $GITHUB_STEP_SUMMARY
          echo '| Lint | ${{ needs.lint.result }} |' >> $GITHUB_STEP_SUMMARY
          echo '| Docs | ${{ needs.docs.result }} |' >> $GITHUB_STEP_SUMMARY